# Generated by Django 3.1.2 on 2020-10-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20201022_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
