# Generated by Django 3.1.2 on 2020-10-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='writing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.writing'),
        ),
    ]
